controller_list:
  - name: fake_chris_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_chris_hand_controller
    joints:
      - joint6
      - joint7